set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports rst]
set_property PACKAGE_PIN F5 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN C6 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN C5 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN B7 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN B6 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN A6 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN A5 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN D8 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN C7 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN E6 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN E5 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN E7 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN D7 [get_ports hsync]
set_property PACKAGE_PIN C4 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN R11 [get_ports go_r]
set_property PACKAGE_PIN V1 [get_ports go_l]
set_property PACKAGE_PIN R17 [get_ports go_d]
set_property PACKAGE_PIN U4 [get_ports go_u]
set_property IOSTANDARD LVCMOS33 [get_ports go_d]
set_property IOSTANDARD LVCMOS33 [get_ports go_l]
set_property IOSTANDARD LVCMOS33 [get_ports go_r]
set_property IOSTANDARD LVCMOS33 [get_ports go_u]





set_property PACKAGE_PIN R15 [get_ports get_meal]
set_property IOSTANDARD LVCMOS33 [get_ports get_meal]


set_property PACKAGE_PIN P3 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports start]

set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN K3 [get_ports {led[15]}]
set_property PACKAGE_PIN M1 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[13]}]
set_property PACKAGE_PIN K6 [get_ports {led[12]}]
set_property PACKAGE_PIN J5 [get_ports {led[11]}]
set_property PACKAGE_PIN H5 [get_ports {led[10]}]
set_property PACKAGE_PIN H6 [get_ports {led[9]}]
set_property PACKAGE_PIN K1 [get_ports {led[8]}]
set_property PACKAGE_PIN K2 [get_ports {led[7]}]
set_property PACKAGE_PIN J2 [get_ports {led[6]}]
set_property PACKAGE_PIN J3 [get_ports {led[5]}]
set_property PACKAGE_PIN H4 [get_ports {led[4]}]
set_property PACKAGE_PIN J4 [get_ports {led[3]}]
set_property PACKAGE_PIN G3 [get_ports {led[2]}]
set_property PACKAGE_PIN G4 [get_ports {led[1]}]
set_property PACKAGE_PIN F6 [get_ports {led[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg2[0]}]
set_property PACKAGE_PIN B4 [get_ports {seven_seg[7]}]
set_property PACKAGE_PIN A4 [get_ports {seven_seg[6]}]
set_property PACKAGE_PIN A3 [get_ports {seven_seg[5]}]
set_property PACKAGE_PIN B1 [get_ports {seven_seg[4]}]
set_property PACKAGE_PIN A1 [get_ports {seven_seg[3]}]
set_property PACKAGE_PIN B3 [get_ports {seven_seg[2]}]
set_property PACKAGE_PIN B2 [get_ports {seven_seg[1]}]
set_property PACKAGE_PIN D5 [get_ports {seven_seg[0]}]
set_property PACKAGE_PIN D4 [get_ports {seven_seg2[7]}]
set_property PACKAGE_PIN E3 [get_ports {seven_seg2[6]}]
set_property PACKAGE_PIN D3 [get_ports {seven_seg2[5]}]
set_property PACKAGE_PIN F4 [get_ports {seven_seg2[4]}]
set_property PACKAGE_PIN F3 [get_ports {seven_seg2[3]}]
set_property PACKAGE_PIN E2 [get_ports {seven_seg2[2]}]
set_property PACKAGE_PIN D2 [get_ports {seven_seg2[1]}]
set_property PACKAGE_PIN H2 [get_ports {seven_seg2[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {enable1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable2[0]}]
set_property PACKAGE_PIN G2 [get_ports {enable1[3]}]
set_property PACKAGE_PIN C2 [get_ports {enable1[2]}]
set_property PACKAGE_PIN C1 [get_ports {enable1[1]}]
set_property PACKAGE_PIN H1 [get_ports {enable1[0]}]
set_property PACKAGE_PIN G1 [get_ports {enable2[3]}]
set_property PACKAGE_PIN F1 [get_ports {enable2[2]}]
set_property PACKAGE_PIN E1 [get_ports {enable2[1]}]
set_property PACKAGE_PIN G6 [get_ports {enable2[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports level]
set_property PACKAGE_PIN P5 [get_ports level]

set_property PACKAGE_PIN K5 [get_ports ps2_clk]
set_property PACKAGE_PIN L4 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ps2_clk]


